import Foundation

let esDict: [String: String] = [
    "api": "ˈapi",
    "framework": "ˈfɾejmwoɾk",
    "frameworks": "ˈfɾejmwoɾks",
    "feedback": "ˈfidbak",
    "backend": "bakˈend",
    "frontend": "fɾonˈtend",
    "endpoint": "ˈendpojnt",
    "endpoints": "ˈendpojnts",
    "stack": "estak",
    "queue": "kju",
    "cache": "kaʃ",
    "branch": "bɾantʃ",
    "merge": "merʃ",
    "commit": "koˈmit",
    "commits": "koˈmits",
    "release": "ɾiˈlis",
    "releases": "ɾiˈlises",
    "feature": "ˈfitʃeɾ",
    "features": "ˈfitʃeɾs",
    "build": "bild",
    "builds": "bilds",
    "router": "ˈɾuteɾ",
    "buffer": "ˈbafeɾ",
    "log": "loɡ",
    "logs": "loɡs",
    "thread": "tɾed",
    "threads": "tɾeds",
    "string": "estɾiŋ",
    "strings": "estɾiŋs",
    "scope": "eskop",
    "container": "konˈtejneɾ",
    "containers": "konˈtejneɾs",
    "developer": "deˈbeloper",
    "developers": "deˈbelopers",
    "testing": "ˈtestin",
    "wrapper": "ˈɾapeɾ",
    "engine": "ˈenʃin",
    "request": "ɾiˈkwest",
    "requests": "ɾiˈkwests",
    "patch": "patʃ",
    "linter": "ˈlinteɾ",
    "lint": "lint",
    "review": "ɾiˈbju",
    "reviews": "ɾiˈbjus",
    "pull": "pul",
    "push": "puʃ",
    "issue": "ˈiʃu",
    "issues": "ˈiʃus",
    "tag": "taɡ",
    "tags": "taɡs",
    "lookup": "ˈlukap",
    "fallback": "ˈfolbak",
    "rollback": "ˈɾolbak",
    "deploy": "deˈploj",
    "callback": "ˈkolbak",
    "callbacks": "ˈkolbaks",
    "workflow": "ˈweɾkflow",
    "workflows": "ˈweɾkflows",
    "pipeline": "ˈpajplajn",
    "pipelines": "ˈpajplajns",
    "dashboard": "ˈdaʃboɾd",
    "dashboards": "ˈdaʃboɾds",
    "frontends": "fɾonˈtends",
    "backends": "bakˈends",
    "scrum": "eskɾum",
    "sprint": "espɾint",
    "sprints": "espɾints",
    "stand-up": "ˈstandap",
    "standup": "ˈstandap",
    "kickoff": "ˈkikof",
    "rollout": "ɾoˈlawt",
    "kanban": "ˈkanban",
    "lookiero": "luˈkjeɾo",
    "deployment": "deˈplojment",
    "deployments": "deˈplojments",
]

let acronyms: Set<String> = [
    "API", "URL", "URI", "HTTP", "HTTPS", "JSON", "XML", "CSS", "HTML", "SQL",
    "REST", "JWT", "UUID", "CORS", "DNS", "SSH", "TCP", "UDP", "RAM", "ROM",
    "CPU", "GPU", "SSD", "HDD", "USB", "PDF", "PNG", "JPG", "SVG", "GIF",
    "AWS", "GCP", "IDE", "MVP", "QA", "UI", "UX", "OS", "IO", "DB",
    "CI", "CD", "TLS", "SSL", "FTP", "VPN", "LAN", "WAN", "VPC", "IAM",
    "S3", "EC2", "EKS", "RDS", "SDK", "ORM", "SPA", "SSR", "CSR", "SSG",
    "PR", "MR", "WIP", "ETA", "TBD", "FYI", "PoC", "POC", "B2B", "B2C",
]

func lookupIPA(word: String, language: String) -> String? {
    guard language == "es" else { return nil }
    return esDict[word.lowercased()]
}

func isAcronym(_ word: String) -> Bool {
    if acronyms.contains(word) { return true }
    return (2...6).contains(word.count) && word.allSatisfy { $0.isASCII && $0.isLetter && $0.isUppercase }
}
